# Site settings
title: "Code & Surf Camp - Le Wagon"
email: contact@lewagon.org
description: "2 semaines de formation et de perfectionnement au code et au surf dans les Landes"
url: http://surfcamp.lewagon.org
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
